INSERT INTO `custom_etcitem` VALUES (10701, 'Sealed Epic Dark Knight Heavy Gloves Design', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10700, 'Sealed Epic Dark Knight Heavy Armor Part', 'false', 'material', 60, 'stackable', 'none', -1, 37565, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10702, 'Sealed Epic Dark Knight Boots Design', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10703, 'Sealed Epic Dark Knight Heavy Helm Pattern', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10704, 'Sealed Epic Dark Knight Light Armor Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10705, 'Sealed Epic Dark Knight Light Gloves Fabric', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10706, 'Sealed Epic Dark Knight Light Boots Design', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10707, 'Sealed Epic Dark Knight Light Helmet Pattern', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10708, 'Sealed Epic Dark Knight Robe Tunic Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10709, 'Sealed Epic Dark Knight Robe Legs Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10710, 'Sealed Epic Dark Knight Robe Gauntlets fabric', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10711, 'Sealed Epic Dark Knight Robe Shoes Design', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10712, 'Sealed Epic Dark Knight Robe Cap Pattern', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10315, 'Sealed Titanium Helmet Part', 'false', 'material', 60, 'stackable', 'none', -1, 37565, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10316, 'Sealed Titanium Breastplate Design', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10317, 'Sealed Titanium Gaiters Design', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10318, 'Sealed Titanium Gauntlets Pattern', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10319, 'Sealed Titanium Boots Pattern', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10320, 'Sealed Titanium Leather Helmet Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10321, 'Sealed Titanium Leather Armor Fabric', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10322, 'Sealed Titanium Leather Pants Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10323, 'Sealed Titanium Leather Gloves Pattern', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10324, 'Sealed Titanium Leather Boots Pattern', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10325, 'Sealed Titanium Circlet Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10326, 'Sealed Titanium Robe Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10327, 'Sealed Titanium Stockings fabric', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10328, 'Sealed Titanium Gloves Design', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10329, 'Sealed Titanium Robe Boots Pattern', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10330, 'Sealed Titanium Shield Pattern', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10033, 'Sealed Dynasty Armor Plate Part', 'false', 'material', 60, 'stackable', 'none', -1, 37565, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10034, 'Sealed Dynasty Armor Gaiters Design', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10035, 'Sealed Dynasty Armor Helm Design', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10036, 'Sealed Dynasty Armor Gloves Pattern', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10037, 'Sealed Dynasty Armor Boots Pattern', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10040, 'Sealed Dynasty Armor Leather Helmet Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10038, 'Sealed Dynasty Armor Leather Fabric', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10039, 'Sealed Dynasty Armor Leather Pants Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10041, 'Sealed Dynasty Armor Gloves Pattern', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10042, 'Sealed Dynasty Armor Leather Boots Pattern', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10045, 'Sealed Dynasty Armor Cap Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10043, 'Sealed Dynasty Armor Robe Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10044, 'Sealed Dynasty Armor Pants fabric', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10046, 'Sealed Dynasty Armor Mittens Design', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10047, 'Sealed Dynasty Armor Slippers Pattern', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10048, 'Sealed Dynasty Shield Pattern', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10100, 'Icarus SawSword Part', 'false', 'material', 60, 'stackable', 'none', -1, 37565, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10101, 'Icarus Disperser Sword Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10102, 'Icarus Spirit Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10103, 'Icarus Heavy Arms Part', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10104, 'Icarus Trident Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10105, 'Icarus Hammer Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10106, 'Icarus Hand Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10107, 'Icarus Hall Part', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10108, 'Icarus Spitter Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10109, 'Icarus Dual Sword Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10110, 'Devil Spear Part', 'false', 'material', 60, 'stackable', 'none', -1, 37565, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10111, 'Medusa Blade Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10112, 'Hades Dagger Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10113, 'Thor Hammer Part', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10114, 'Odin Cleaver Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10115, 'Artemis Bow Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10116, 'Zeus Mace Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10117, 'Ares Fists Part', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10118, 'Aphrodite Staff Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10119, 'Dual Medusa Blade Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10120, 'Dynasty Rapier Part', 'false', 'material', 60, 'stackable', 'none', -1, 37565, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10121, 'Dynasty Ancient Sword Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10122, 'Dynasty Blade Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10123, 'Dynasty Two Handed Sword Part', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10124, 'Dynasty Magic Sword Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10125, 'Dynasty Bow Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10126, 'Dynasty Dagger Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10127, 'Dynasty Spear Part', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10128, 'Dynasty Hammer Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10129, 'Dynasty Staff Part', 'false', 'material', 60, 'stackable', 'none', -1, 40365, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10130, 'Dynasty Fist Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (20324, 'SonicTi Adversiting', 'false', 'none', 0, 'stackable', 'none', -1, 1, 0, 'true', 'true', 'false', 'false', 'q_gold_dragon', 'none');
INSERT INTO `custom_etcitem` VALUES (10131, 'Dynasty Dual Rapier Part', 'false', 'material', 60, 'stackable', 'none', -1, 14047, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (10133, 'Dynasty Shield Part', 'false', 'material', 60, 'stackable', 'none', -1, 12329, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (20325, 'Adversiting', 'false', 'none', 9999, 'stackable', 'none', -1, 1000, 0, 'true', 'true', 'true', 'true', 'q_gold_dragon', 'none');
INSERT INTO `custom_etcitem` VALUES (22222, 'Ticket Donator', 'false', 'none', 0, 'stackable', 'none', -1, 2000000, 0, 'true', 'true', 'true', 'true', 'q_gold_dragon', 'none');
INSERT INTO `custom_etcitem` VALUES (15000, 'Ticket For Set Titanium', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15001, 'Ticket For Set Dynasty', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15002, 'Ticket For Set Dark Knight', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15003, 'Magic Fusion', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15004, 'Reagent For Right', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15005, 'Superior Ancient Adena', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15006, 'Superior Adena', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15007, 'Adena GTS', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15008, 'Supleme Medal', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15009, 'Superior Supleme Medal', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15010, 'Glittering Supleme Medal', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15011, 'Superior Glittering Suple Medal', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15012, 'Medal of Champion', 'true', 'none', 0, 'stackable', 'none', -1, 12465, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15013, 'Nobless Adena', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15014, 'Hero Adena', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15015, 'Super Presente', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15016, 'Flores de Abril', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15017, 'Flores de Maio', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15018, 'Flores de Junho', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (15019, 'Flores de Julho', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'C4Item', 'none');
INSERT INTO `custom_etcitem` VALUES (9616, 'Kalie Token', 'false', 'none', 1, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'by Smallz', 'none');
INSERT INTO `custom_etcitem` VALUES (9617, 'Kalie Box', 'false', 'none', 1, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'by Smallz', 'none');
INSERT INTO `custom_etcitem` VALUES (9865, 'Candy Basket', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Candy Basket', 'none');
INSERT INTO `custom_etcitem` VALUES (9866, 'Pig Candy', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pig Candy', 'none');
INSERT INTO `custom_etcitem` VALUES (9867, 'Easter Candy', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Easter Candy', 'none');
INSERT INTO `custom_etcitem` VALUES (9868, 'Halloween King Pumpkin', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Halloween King Pumpkin', 'none');
INSERT INTO `custom_etcitem` VALUES (9869, 'Halloween Pumpkin', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Halloween Pumpkin', 'none');
INSERT INTO `custom_etcitem` VALUES (9870, 'Pig Adena : Gold', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pig Adena : Gold', 'none');
INSERT INTO `custom_etcitem` VALUES (9871, 'Pig Adena : Bronze', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pig Adena : Bronze', 'none');
INSERT INTO `custom_etcitem` VALUES (9872, 'Supreme Torch', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Supreme Torch', 'none');
INSERT INTO `custom_etcitem` VALUES (9873, 'Darkness Torch', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Darkness Torch', 'none');
INSERT INTO `custom_etcitem` VALUES (9874, 'Forest Letter', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Forest Letter', 'none');
INSERT INTO `custom_etcitem` VALUES (9875, 'Candy Basket', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Adventurer Letter', 'none');
INSERT INTO `custom_etcitem` VALUES (9876, 'Pig Candy', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Fresh Milk', 'none');
INSERT INTO `custom_etcitem` VALUES (9877, 'Easter Candy', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20020, 'Festival Stone 1', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20021, 'Festival Stone 2', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20022, 'Festival Stone 3', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20023, 'Festival Stone 4', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20024, 'Festival Stone 5', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20025, 'Festival Stone 6', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20026, 'Festival Stone 7', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20027, 'Festival Stone 8', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20028, 'Festival Stone 9', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20029, 'Festival Stone 10', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20139, 'Pig', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20140, 'Cat', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20141, 'IconeL2', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20319, 'Gold Coin', 'false', 'none', 0, 'stackable', 'none', -1, 2000000, 0, 'true', 'true', 'true', 'true', 'q_gold_dragon', 'none');
INSERT INTO `custom_etcitem` VALUES (20313, 'Set Crystal', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'false', 'true', 'true', 'false', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20314, 'Set Crystal', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'false', 'true', 'true', 'false', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20315, 'Set Crystal', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'false', 'true', 'true', 'false', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20316, 'Set Crystal', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'false', 'true', 'true', 'false', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20317, 'Set Crystal', 'false', 'none', 0, 'stackable', 'none', -1, 0, 0, 'false', 'true', 'true', 'false', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20318, 'Soul Crystal Boss', 'false', 'quest', 0, 'stackable', 'none', -1, 0, 0, 'false', 'true', 'true', 'false', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (20191, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20192, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20193, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20194, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20195, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20196, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20197, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20198, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20199, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20200, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20201, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20202, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20203, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20204, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20205, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20206, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20207, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20208, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20209, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20210, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20211, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20212, 'Olly Potions', 'false', 'potion', 0, 'stackable', 'none', -1, 0, 0, 'true', 'true', 'true', 'true', 'quick_healing_potion', 'potion');
INSERT INTO `custom_etcitem` VALUES (20240, 'Ticket AIO Eternity', 'false', 'none', 0, 'stackable', 'none', -1, 500000, 0, 'true', 'true', 'true', 'true', 'Pure Gold Bar', 'none');
INSERT INTO `custom_etcitem` VALUES (22223, 'Ticket Donator Old Coin', 'false', 'none', 0, 'stackable', 'none', -1, 2000000, 0, 'true', 'true', 'true', 'true', 'q_gold_dragon', 'none');
INSERT INTO `custom_etcitem` VALUES (20274, 'Topaz Material', 'false', 'none', 0, 'stackable', 'none', -1, 2000000, 0, 'true', 'true', 'true', 'true', 'q_gold_dragon', 'none');
INSERT INTO `custom_etcitem` VALUES (20275, 'Ruby Material', 'false', 'none', 0, 'stackable', 'none', -1, 2000000, 0, 'true', 'true', 'true', 'true', 'q_gold_dragon', 'none');
INSERT INTO `custom_etcitem` VALUES (20276, 'Topaz', 'false', 'none', 0, 'stackable', 'none', -1, 2000000, 0, 'true', 'true', 'true', 'true', 'q_gold_dragon', 'none');
INSERT INTO `custom_etcitem` VALUES (20277, 'Ruby', 'false', 'none', 0, 'stackable', 'none', -1, 2000000, 0, 'true', 'true', 'true', 'true', 'q_gold_dragon', 'none');
INSERT INTO `custom_etcitem` VALUES (20320, 'Blood Coin', 'false', 'none', 0, 'stackable', 'none', -1, 2000000, 0, 'true', 'true', 'true', 'true', 'q_gold_dragon', 'none');
INSERT INTO `custom_etcitem` VALUES (20326, 'Adversiting', 'false', 'none', 9999, 'stackable', 'none', -1, 1000, 0, 'true', 'true', 'true', 'true', 'q_gold_dragon', 'none');
INSERT INTO `custom_etcitem` VALUES (20331, 'Gold Medal', 'false', 'none', 10, 'stackable', 'none', -1, 1000, 0, 'true', 'true', 'true', 'true', 'q_gold_dragon', 'none');
INSERT INTO `custom_etcitem` VALUES (20328, 'Adversiting', 'false', 'none', 9999, 'stackable', 'none', -1, 1000, 0, 'true', 'true', 'true', 'true', 'q_gold_dragon', 'none');
INSERT INTO `custom_etcitem` VALUES (20330, 'Adversiting', 'false', 'none', 9999, 'stackable', 'none', -1, 1000, 0, 'true', 'true', 'true', 'true', 'q_gold_dragon', 'none');
