INSERT INTO `icp_votesystem_tops` VALUES (1, 'TOP SERVERS 200', '13522', 1);
INSERT INTO `icp_votesystem_tops` VALUES (2, 'L2jBrasil', 'sem_id', 0);
INSERT INTO `icp_votesystem_tops` VALUES (3, 'GameSites200', 'sem_id', 0);
INSERT INTO `icp_votesystem_tops` VALUES (4, 'Top Lineage 2', 'sem_id', 0);
INSERT INTO `icp_votesystem_tops` VALUES (5, 'GTOP100', '89201', 1);
INSERT INTO `icp_votesystem_tops` VALUES (6, 'L2 TOP ZONE', 'sem_id', 0);
INSERT INTO `icp_votesystem_tops` VALUES (7, 'MMORPG', '62437', 1);
INSERT INTO `icp_votesystem_tops` VALUES (8, 'HOPZONE', 'sem_id', 0);
INSERT INTO `icp_votesystem_tops` VALUES (9, 'TOPGS200', 'sem_id', 0);
INSERT INTO `icp_votesystem_tops` VALUES (10, 'Top 100 Arena', '88506', 1);
INSERT INTO `icp_votesystem_tops` VALUES (11, 'Top MMO', 'sem_id', 0);
INSERT INTO `icp_votesystem_tops` VALUES (12, 'Top200Games', 'sem_id', 0);
